## 파이썬 머신러닝
# 나만의 분류기 만들기

In [1]:
import numpy as np

In [2]:
from sklearn.base import BaseEstimator, ClassifierMixin

In [3]:
### 각 클래스 중심점에서의 거리로 판별
class MyClassifier(BaseEstimator, ClassifierMixin):
    def __init__(self):
        self.result=0
        self.n_class=0
        self.centers = []
        self.X = None
        self.y = None
        
    def fit(self, X, y):
        #self.result = np.argmax(np.bincount(y))
        self.X = X
        self.y = y
        
        self.n_class = y.max()+1
        for i in range(self.n_class):
            x = X[y==i]
            self.centers.append(x.mean(axis=0))
        
        return self
        
    def predict(self, X):
        #pred_y = np.zeros(len(X)) + self.result
        
        pred_y=[]
        for x in X:
            l = [((x-c)**2).sum() for c in self.centers]
            pred_y.append(np.argmin(l))
            
        return np.array(pred_y)

In [4]:
from sklearn.datasets import load_iris

iris = load_iris()

In [5]:
model = MyClassifier()
model.fit(iris.data, iris.target)
model.score(iris.data, iris.target)

0.9266666666666666

In [6]:
model.predict(iris.data)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [7]:
model.centers

[array([5.006, 3.428, 1.462, 0.246]),
 array([5.936, 2.77 , 4.26 , 1.326]),
 array([6.588, 2.974, 5.552, 2.026])]

In [8]:
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()

In [9]:
X_norm = (cancer.data-cancer.data.mean(axis=0))/cancer.data.std(axis=0)

In [10]:
model = MyClassifier()
model.fit(X_norm, cancer.target)
model.score(X_norm, cancer.target)

0.9314586994727593